import type {Metadata} from "next";
import {Space_Grotesk, JetBrains_Mono} from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import FooterSlide from "@/components/FooterSlide";
import Script from "next/script";
import CustomAnimations from "@/components/CustomAnimation";
import Footer from "@/components/Footer";

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
});
const jet = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "CapyData | The Chillest Data Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <Script
          src="https://unpkg.com/lucide@latest"
          strategy="beforeInteractive"
        />
      </head>

      <body
        className={`${space.variable} ${jet.variable} overflow-x-hidden selection:bg-yuzu selection:text-black`}>
        <CustomAnimations />
        <Navbar />
        {children}
        <Footer />
        <FooterSlide />
      </body>
    </html>
  );
}
